# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspapp', '0005_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
    ]
